### ISSUE TITLE
Problem with JuMP.fix command

### ISSUE THREAD

**Issue by trivedymk** [chkwon/Complementarity.jl#30]
Hi,

I've been working on a complementarity model and it involves fixing some variables. To do this in JuMP i've attempted to use

`for i in suppliers, s in seasons, t in timeperiods
    JuMP.fix(s_contract["EU","UK",i,s,t],0)
    JuMP.fix(s_spot["EU","UK",i,s,t],0)
end`

However, when I run this with complementarity I get the error

>  "setvalue for fixed variables is no longer supported. Use JuMP.fix instead.".

https://github.com/chkwon/Complementarity.jl/blob/9f2405d969fe83b2d316e5a8354434c264e611cb/src/mcp.jl#L145

So setvalue here needs to be changed to JuMP.fix to reflect the updated jump build I think.

**Comment by chkwon** [comment]
Thanks for the update. I'll take a look surely. By the way, i don't think I can work on it sometime soon as I am in an international travel.

**Comment by chkwon** [comment]
I don't understand what fixing a variable in a complementarity problem means. Does your complementarity problem have multiple solutions? 

Does the PATH solver or other complementarity problem solvers (if any) support such variable fixing functionality?

**Comment by boxblox** [comment]
I am also getting this JuMP.fix error... I believe trivedymk might be right that setvalue has been deprecated.  Any solver should be able to handle this type of fixing... an equivalent statement would be to say that JuMP.fix(x, 5) or 5 <= x <=5.  In a GAMS environment you can do this with PATH.

**Comment by chkwon** [comment]
Closing for the new version of PATHSolver.jl https://github.com/chkwon/PATHSolver.jl/pull/44
