### ISSUE TITLE
The complementarity macro (@complementarity) does not include JuMP variables of SparseAxisArray type

### ISSUE THREAD

**Issue by QinBa** [chkwon/Complementarity.jl#37]
I am using __Julia 1.03__,  __IJulia 1.17.0__, __JuMP 0.19.0__. The problem is that the type SparseAxisArray has no field axes. 

An example demonstrating the problem is as follow. 
```julia
using Complementarity, JuMP

m = MCPModel()
@variable(m, x[i=1:4; i%2==0] >= 0)
@mapping(m, F[i=1:4; i%2==0], x[i]+2)
@complementarity(m, F, x)
```
Error message: 
>type SparseAxisArray has no field axes
>
>Stacktrace:
> [1] getproperty(::Any, ::Symbol) at ./sysimg.jl:18
> [2] top-level scope at /Users/XXX/.julia/packages/Complementarity/Gag1Y/src/mcp.jl:371
> [3] top-level scope at In[1]:6

**Comment by chkwon** [comment]
@QinBa At this moment, the package does not support conditional indexing such as `i%2==0`.  You might do:

```julia
using Complementarity, JuMP

m = MCPModel()
@variable(m, x[i=1:4] >= 0)
@mapping(m, F[i=1:4], x[i]+2)

for i in 1:4
  if i%2 == 0
    @complementarity(m, F[i], x[i])
  end
end
```

**Comment by QinBa** [comment]
Thank you for the response!
