### ISSUE TITLE
Failure to Precompile PATHSolver

### ISSUE THREAD

**Issue by Jovansam** [chkwon/Complementarity.jl#40]
Building PATHSolver → `C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\build.log`
┌ Error: Error building `PATHSolver`: 
│ [ Info: Attempting to create directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\usr\lib
│ [ Info: Attempting to create directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Attempting to create directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\downloads
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Downloading file https://github.com/ampl/pathlib/archive/4.7.03.zip
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Done downloading file https://github.com/ampl/pathlib/archive/4.7.03.zip
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Attempting to create directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps
│ [ Info: Directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps already exists
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ ERROR: LoadError: IOError: could not spawn `'C:\Users\KitchenComputer\AppData\Local\Julia-1.3.1\bin\7z.exe' x 'C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\downloads\pathlib.zip' -y '-oC:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src'`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99
│  [2] setup_stdios(::Base.var"#554#555"{Cmd}, ::Array{Any,1}) at .\process.jl:112
│  [3] _spawn at .\process.jl:111 [inlined]
│  [4] #run#565(::Bool, ::typeof(run), ::Cmd) at .\process.jl:439
│  [5] run(::Cmd) at .\process.jl:438
│  [6] run(::BinDeps.PathRule) at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\BinDeps.jl:503
│  [7] run(::BinDeps.SynchronousStepCollection) at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\BinDeps.jl:521 (repeats 2 times)
│  [8] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\dependencies.jl:944     
│  [9] satisfy!(::BinDeps.LibraryDependency) at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\dependencies.jl:922
│  [10] top-level scope at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [11] include at .\boot.jl:328 [inlined]
│  [12] include_relative(::Module, ::String) at .\loading.jl:1105
│  [13] include(::Module, ::String) at .\Base.jl:31
│  [14] include(::String) at .\client.jl:424
│  [15] top-level scope at none:5
│ in expression starting at C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\build.jl:96
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649
  Building CodecZlib ─→ `C:\Users\KitchenComputer\.julia\packages\CodecZlib\5t9zO\deps\build.log`
  Building MbedTLS ───→ `C:\Users\KitchenComputer\.julia\packages\MbedTLS\a1JFn\deps\build.log`
  Building CodecBzip2 → `C:\Users\KitchenComputer\.julia\packages\CodecBzip2\T5yr7\deps\build.log`
[ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]
[ Info: Precompiling Complementarity [a9b2a840-c9d5-5181-a245-8df664c2d6e7]
ERROR: LoadError: PATHSolver not properly installed. Please re-build PATHSolver.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\src\PATHSolver.jl:15
 [3] include at .\boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1105
 [5] include(::Module, ::String) at .\Base.jl:31
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:330 [inlined]
 [8] eval(::Expr) at .\client.jl:425
 [9] top-level scope at .\none:3
in expression starting at C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\src\PATHSolver.jl:12
ERROR: LoadError: Failed to precompile PATHSolver [f5f7c340-0bb3-5c69-969a-41884d311d1b] to C:\Users\KitchenComputer\.julia\compiled\v1.3\PATHSolver\xyGrF_jwUCN.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\KitchenComputer\.julia\packages\Complementarity\Gag1Y\src\Complementarity.jl:18
julia>

**Comment by chrished** [comment]
I think the "PATHSolver.jl" in the julia registry is not up to date. Does the following work?:
```julia 
]add https://github.com/chkwon/PATHSolver.jl.git
```

**Comment by Jovansam** [comment]
Thanks Chris. After Pkg.rm("PATHsolver"), I ran

] add https://github.com/chkwon/PATHSolver.jl.git
using Pkg; Pkg.build("PATHSolver")  or using Pkg; Pkg.build("Complementarity")

I still have the same problem.

**Comment by chkwon** [comment]
A new version is registered. Can you upgrade and test?

**Comment by Jovansam** [comment]
@chkwon, thanks for the upgrade and your work with this package.

I tested it with following piece of code:

```jl
using JuMP, Ipopt, Complementarity
m = Model(Ipopt.Optimizer)
@variable(m, x>=0)
@NLobjective(m, Min, x^3)
@complements(m, 0 <= x+2,   x >= 0)
optimize!(m)
@show value.(x)
```
works well in the REPL, Julia VScode, and Atom-Juno but, I still get errors in Atom-Hydrogen. Below is the new error message.

The error message:

>┌ Info: Precompiling Complementarity [a9b2a840-c9d5-5181-a245-8df664c2d6e7]
└ @ Base loading.jl:1260
ERROR: LoadError: PATHSolver not properly installed. Please re-build PATHSolver.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\src\PATHSolver.jl:15
 [3] include(::Module, ::String) at .\Base.jl:377
 [4] top-level scope at none:2
 [5] eval at .\boot.jl:331 [inlined]
 [6] eval(::Expr) at .\client.jl:449
 [7] top-level scope at .\none:3
in expression starting at C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\src\PATHSolver.jl:12
ERROR: LoadError: Failed to precompile PATHSolver [f5f7c340-0bb3-5c69-969a-41884d311d1b] to C:\Users\KitchenComputer\.julia\compiled\v1.4\PATHSolver\xyGrF_PBNxJ.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
 [6] include(::Module, ::String) at .\Base.jl:377
 [7] top-level scope at none:2
 [8] eval at .\boot.jl:331 [inlined]
 [9] eval(::Expr) at .\client.jl:449
 [10] top-level scope at .\none:3
in expression starting at C:\Users\KitchenComputer\.julia\packages\Complementarity\Gag1Y\src\Complementarity.jl:18
Failed to precompile Complementarity [a9b2a840-c9d5-5181-a245-8df664c2d6e7] to C:\Users\KitchenComputer\.julia\compiled\v1.4\Complementarity\ORstz_PBNxJ.ji.
>
>Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
 [6] top-level scope at In[2]:1

**Comment by Jovansam** [comment]
@chkwon there is this piece of code that you have on [here](https://github.com/chkwon/Complementarity.jl)

```
using Complementarity, JuMP
m = MCPModel()
@variable(m, x >= 0)
@mapping(m, F, x+2)
@complementarity(m, F, x)
status = solveMCP(m)
@show result_value(x)
```
I cant get it to work because of solveMCP(m). How has this and  the "result_value(x)" changed in JuMP v0.21.1?

Thanks for you response.

**Comment by Jovansam** [comment]
@chkwon 

I do not whether this might be helpful, but when I run code that uses "Complementarity.jl" it says:
>[ Info: Precompiling Complementarity [a9b2a840-c9d5-5181-a245-8df664c2d6e7]
┌ Warning: Package Complementarity does not have LinearAlgebra in its dependencies:
│ - If you have Complementarity checked out for development and have
│   added LinearAlgebra as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Complementarity
└ Loading LinearAlgebra into Complementarity from project dependency, future warnings for Complementarity are suppressed.

**Comment by chkwon** [comment]
I don't know how Atom-Hydrogen works, but it seems that it cannot load the PATH solver library correctly.  Can you try `using Pkg; Pkg.build("PATHSolver")` within Atom-Hydrogen to see if it works?

**Comment by Jovansam** [comment]
@chkwon:

I did, but another error.

> Building SpecialFunctions → `C:\Users\KitchenComputer\.julia\packages\SpecialFunctions\fvheQ\deps\build.log`
   Building PATHSolver ──────→ `C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\build.log`
┌ Error: Error building `PATHSolver`: 
│ [ Info: Attempting to create directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\usr\lib
│ [ Info: Attempting to create directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Attempting to create directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\downloads
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Downloading file https://github.com/ampl/pathlib/archive/4.7.03.zip
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Done downloading file https://github.com/ampl/pathlib/archive/4.7.03.zip
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ [ Info: Attempting to create directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps
│ [ Info: Directory C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps already exists
│ [ Info: Changing directory to C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src
│ ERROR: LoadError: IOError: could not spawn `'C:\Users\KitchenComputer\AppData\Local\Programs\Julia\Julia-1.4.0\bin\7z.exe' x 'C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\downloads\pathlib.zip' -y '-oC:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\src'`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99
│  [2] #550 at .\process.jl:112 [inlined]
│  [3] setup_stdios(::Base.var"#550#551"{Cmd}, ::Array{Any,1}) at .\process.jl:196
│  [4] _spawn at .\process.jl:111 [inlined]
│  [5] run(::Cmd; wait::Bool) at .\process.jl:439
│  [6] run(::Cmd) at .\process.jl:438
│  [7] run(::BinDeps.PathRule) at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\BinDeps.jl:503
│  [8] run(::BinDeps.SynchronousStepCollection) at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\BinDeps.jl:521 (repeats 2 times)
│  [9] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\dependencies.jl:944
│  [10] satisfy!(::BinDeps.LibraryDependency) at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\dependencies.jl:922
│  [11] top-level scope at C:\Users\KitchenComputer\.julia\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [12] include(::String) at .\client.jl:439
│  [13] top-level scope at none:5
│ in expression starting at C:\Users\KitchenComputer\.julia\packages\PATHSolver\lRj12\deps\build.jl:96
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892

At least it was great knowing that it works with Juno. 😄
