### ISSUE TITLE
Questions of using complementarity.jl to build the computable general equilibrium model

### ISSUE THREAD

**Issue by KennethAnn** [chkwon/Complementarity.jl#68]
Dear Professor Kwon, I am now using complementarity.jl to build a computable general equilibrium (CGE) model, which is in general established in GAMS software. A question is whether the **NLconstraint** can be used in MCPModel(), since I want to combine the **nonlinear equations** and MCP structure together.

**Comment by chkwon** [comment]
`@mapping` is just an alias of `@NLexpression`. You can use nonlinear terms in `@mapping`.  You cannot use `@NLconstraint`.

**Comment by KennethAnn** [comment]
Thanks. I am curious about the model structure interface whether it could print the real value of each @mapping when I print the model. To do so, I can directly obtain the value of subexpressions, which could be benefit for checking the balance of equations.
![image](https://user-images.githubusercontent.com/89579419/188252946-2258959f-7051-4033-8e2b-3440fd196999.png)
